image: Visual Studio 2017
shallow_clone: true

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.3"
      PYTHON_ARCH: "32"
      nodejs_version: "8.9.1"
      APPVEYOR: "true"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g yarn
  - yarn
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install -U pip
  - pip install -t ./pythonFiles/experimental/ptvsd git+https://github.com/Microsoft/ptvsd/
  - python --version
  - python -m easy_install -U setuptools
  - "%PYTHON%/Scripts/pip.exe install --upgrade -r requirements.txt"

build_script:
  - ps: git clone https://github.com/Microsoft/PTVS.git c:/Projects/PTVS
  - ps: c:\Projects\PTVS
  - ps: git checkout origin/master
  - ps: cd c:\Projects\PTVS\Python\Product\VSCode\AnalysisVsc
  - ps: dotnet --info
  - ps: dotnet build
  - ps: xcopy /S /D C:\Projects\PTVS\BuildOutput\VsCode\raw c:\Projects\vscode-python\analysis

test_script:
  - yarn run clean
  - yarn run vscode:prepublish
  - yarn run testDebugger --silent
  - yarn run testSingleWorkspace --silent
  - yarn run testMultiWorkspace --silent

build: off
