[tool.black]
exclude = '''

(
  /(
    .data
    | .vscode
    | lib
  )/
)
'''

[tool.pyright]
exclude = ['lib']
extraPaths = ['lib/python', 'lib/jedilsp']
ignore = [
    # Ignore all pre-existing code with issues
    'get-pip.py',
    'install_debugpy.py',
    'tensorboard_launcher.py',
    'testlauncher.py',
    'visualstudio_py_testlauncher.py',
    'testing_tools/unittest_discovery.py',
    'testing_tools/adapter/util.py',
    'testing_tools/adapter/pytest/_discovery.py',
    'testing_tools/adapter/pytest/_pytest_item.py',
    'tests/debug_adapter/test_install_debugpy.py',
    'tests/testing_tools/adapter/.data',
    'tests/testing_tools/adapter/test___main__.py',
    'tests/testing_tools/adapter/test_discovery.py',
    'tests/testing_tools/adapter/test_functional.py',
    'tests/testing_tools/adapter/test_report.py',
    'tests/testing_tools/adapter/test_util.py',
    'tests/testing_tools/adapter/pytest/test_cli.py',
    'tests/testing_tools/adapter/pytest/test_discovery.py',
]

[tool.ruff]
line-length = 140

exclude = ["lib", ".vscode", ".data"]

[tool.ruff.lint]
# Compatible w/ ruff formatter. https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
select = [
  "F",  # Pyflakes
  "E4", "E7", "E9",  # pycodestyle
  "I",  # isort
  "N",  # pep8-naming
  "D2", "D400", "D403", "D419",  # pydocstyle
  "UP",  # pyupgrade
  "YTT",  # flake8-2020
  "ASYNC",  # flake8-async
  "B",  # flake8-bugbear
  "A",  # flake8-builtins
  "C",  # flake8-comprehensions
  "DTZ",  # flake8-dasetimez
  "INP",  # flake8-no-pep420
  "PIE",  # flake8-pie
  "PYI",  # flake8-pyi
  # flake8-pytest-style
  "PT006", "PT007", "PT009", "PT012", "PT014", "PT015", "PT016", "PT017", "PT018", "PT019",
  "PT020", "PT021", "PT022", "PT024", "PT025", "PT026", "PT027",
  "RSE",  # flake8-raise
  "RET502", "RET503", "RET504",  # flake8-return
  "SLF",  # flake8-self
  "SIM",  # flake8-simplify
  "TCH",  # flake8-type-checking
  "ARG",  # flake8-unused-argument
  "PTH",  # flake8-pathlib
  "ERA",  # eradicate
  "PD",  # pandas-vet
  "PGH",  # pygrep-hooks
  "NPY",  # NymPy-specific rules
  "PERF",  # Perflint
  "RUF",  # Ruff-specific rules
]

ignore = ["N818", "PT027", "PTH123", "PGH001"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"
