name: CI

on:
  push:
    branches:
      # Run the CI workflow only on master for microsoft/vscode-python for now.
      - test*

env:
  PYTHON_VERSION: 3.8
  MOCHA_REPORTER_JUNIT: true # Use the mocha-multi-reporters and send output to both console (spec) and JUnit (mocha-junit-reporter). Also enables a reporter which exits the process running the tests if it haven't already.
  CACHE_NPM_DEPS: cache-npm
  CACHE_OUT_DIRECTORY: cache-out-directory
  CACHE_PIP_DEPS: cache-pip
  # Key for the cache created at the end of the the 'Cache ./pythonFiles/lib/python' step.
  CACHE_PYTHONFILES: cache-pvsc-pythonFiles
  ARTIFACT_NAME_VSIX: ms-python-insiders-vsix
  COVERAGE_REPORTS: tests-coverage-reports
  TEST_RESULTS_DIRECTORY: .
  LKG_TAG: ci-lkg

jobs:
  ### Initialization: retrieve, install and cache dependencies
  python-deps:
    name: Install Python Requirements
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/vscode-python'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show all env vars
        run: |
          printenv
        shell: bash

      - name: Use Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install Python requirements
        run: |
          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade -r requirements.txt
          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python/old_ptvsd --no-cache-dir --implementation py --no-deps --upgrade 'ptvsd==4.3.2'

      - name: Install debugpy wheels
        run: |
          python -m pip install wheel
          python -m pip --disable-pip-version-check install -r build/debugger-install-requirements.txt
          python ./pythonFiles/install_debugpy.py

      # Retrieve the list of debugpy versions from PyPI in order to increase the specificity of the pip cache key,
      # so that the cache gets invalidated as necessary.
      # See https://github.com/microsoft/vscode-python/pull/9843#discussion_r373635221
      - name: curl PyPI to get debugpy versions
        run: curl --output debugpy.json https://pypi.org/pypi/debugpy/json

      - name: Cache pip files
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-${{env.CACHE_PIP_DEPS}}-pip-${{env.PYTHON_VERSION}}-${{hashFiles('requirements.txt')}}-${{hashFiles('build/debugger-install-requirements.txt')}}-${{hashFiles('debugpy.json')}}

      - name: Cache ./pythonFiles/lib/python
        uses: actions/cache@v1
        with:
          path: ./pythonFiles/lib/python
          key: ${{runner.os}}-${{env.CACHE_PYTHONFILES}}-pythonFiles-${{env.PYTHON_VERSION}}-${{hashFiles('requirements.txt')}}-${{hashFiles('build/debugger-install-requirements.txt')}}-${{hashFiles('debugpy.json')}}

  js-ts-deps:
    name: Install npm dependencies
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/vscode-python'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies (npm ci)
        run: npm ci --prefer-offline

      - name: Cache npm files
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{env.CACHE_NPM_DEPS}}-${{hashFiles('package-lock.json')}}

  ### Hygiene + VSIX upload
  compile-hygiene:
    name: Compile, lint, check for errors
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/vscode-python'
    needs: [js-ts-deps, python-deps]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show all env vars
        run: |
          printenv
        shell: bash

      - name: Retrieve cached npm files
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{env.CACHE_NPM_DEPS}}-${{hashFiles('package-lock.json')}}

      - name: Install dependencies (npm ci)
        run: npm ci --prefer-offline

      - name: Run gulp prePublishNonBundle
        run: npx gulp prePublishNonBundle

      - name: Cache the out/ directory
        uses: actions/cache@v1
        with:
          path: ./out
          key: ${{runner.os}}-${{env.CACHE_OUT_DIRECTORY}}-${{hashFiles('src/**')}}

      - name: Check dependencies
        run: npm run checkDependencies

      - name: Run linting on TypeScript code
        run: npx tslint --project tsconfig.json

      - name: Run prettier on TypeScript code
        run: npx prettier 'src/**/*.ts*' --check

      - name: Run prettier on JavaScript code
        run: npx prettier 'build/**/*.js' --check

      - name: Use Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Run Black on Python code
        run: |
          python -m pip install -U black
          python -m black . --check
        working-directory: pythonFiles

  build-vsix:
    name: Build VSIX
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/vscode-python'
    needs: [python-deps, js-ts-deps]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve cached npm files
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{env.CACHE_NPM_DEPS}}-${{hashFiles('package-lock.json')}}

      - name: curl PyPI to get debugpy versions
        run: curl --output debugpy.json https://pypi.org/pypi/debugpy/json

      - name: Retrieve cached pythonFiles/ directory
        uses: actions/cache@v1
        with:
          path: ./pythonFiles/lib/python
          key: ${{runner.os}}-${{env.CACHE_PYTHONFILES}}-pythonFiles-${{env.PYTHON_VERSION}}-${{hashFiles('requirements.txt')}}-${{hashFiles('build/debugger-install-requirements.txt')}}-${{hashFiles('debugpy.json')}}

      - name: Install dependencies (npm ci)
        run: npm ci --prefer-offline

      - name: Clean directory
        run: npm run clean

      # Use the GITHUB_RUN_ID environment variable to update the build number.
      # GITHUB_RUN_ID is a unique number for each run within a repository.
      # This number does not change if you re-run the workflow run.
      - name: Update build number
        run: npm run updateBuildNumber -- --buildNumber $GITHUB_RUN_ID

      - name: Package the VSIX
        run: npm run package

      - uses: actions/upload-artifact@v1
        with:
          name: ${{env.ARTIFACT_NAME_VSIX}}
          path: ms-python-insiders.vsix

  smoke-tests:
    name: Smoke tests
    # The value of runs-on is the OS of the current job (specified in the strategy matrix below) instead of being hardcoded.
    runs-on: ${{ matrix.os }}
    needs: [build-vsix]
    if: github.repository == 'microsoft/vscode-python'
    strategy:
      fail-fast: false
      matrix:
        # We're not running CI on macOS for now because it's one less matrix entry to lower the number of runners used,
        # macOS runners are expensive, and we assume that Ubuntu is enough to cover the UNIX case.
        os: [ubuntu-latest, windows-latest]
        python: [3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show all env vars
        run: |
          printenv
        shell: bash

      - name: Use Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}

      - name: Retrieve cached npm files
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{env.CACHE_NPM_DEPS}}-${{hashFiles('package-lock.json')}}

      - name: Install dependencies (npm ci)
        run: npm ci --prefer-offline

      - name: pip install system test requirements
        run: |
          python -m pip install --upgrade -r build/test-requirements.txt
          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade -r requirements.txt
          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python/old_ptvsd --no-cache-dir --implementation py --no-deps --upgrade 'ptvsd==4.3.2'
          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade --pre debugpy
        shell: bash

      - name: pip install ipython requirements
        run: |
          python -m pip install numpy
          python -m pip install --upgrade -r ./build/ipython-test-requirements.txt

      - name: pip install jupyter
        run: |
          python -m pip install --upgrade jupyter

      - name: Download VSIX
        uses: actions/download-artifact@v1
        with:
          name: ${{env.ARTIFACT_NAME_VSIX}}

      # Extract the artifact from its download folder (./${{env.ARTIFACT_NAME_VSIX}}) to the repo root,
      # then delete the download folder and compile the source code.
      - name: Prepare for smoke tests
        run: |
          mv ${{env.ARTIFACT_NAME_VSIX}}/* .
          rm -r ${{env.ARTIFACT_NAME_VSIX}}
          npx tsc -p ./
        shell: bash

      - name: Set CI_PYTHON_PATH and CI_DISABLE_AUTO_SELECTION
        run: |
          echo "::set-env name=CI_PYTHON_PATH::python"
          echo "::set-env name=CI_DISABLE_AUTO_SELECTION::1"
        shell: bash

      - name: Run smoke tests
        env:
          DISPLAY: 10
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: node ./out/test/smokeTest.js
