name: Issues Summary

on:
  schedule:
    - cron: '0 0 * * 2' # Runs every Tuesday at midnight
  workflow_dispatch:

jobs:
  generate-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run summary script
        run: python scripts/generate_summary.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
