name: 'Lock Issues'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write

concurrency:
  group: lock

jobs:
  lock-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-inactive-days: '30'
          issue-lock-comment: 'This issue has been automatically locked since there has been no recent activity since its closing. Please open a new issue if you have a related bug.'
          process-only: 'issues'
