name: Packages Update Check

on:
  schedule:
    # Run at UTC 00:00 Mon
    - cron: '0 0 * * 1'

jobs:
  check-PyPI:
    name: Check for package updates on PyPI and create issue if tests fail
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Update pip, install wheel
        run: python -m pip install -U pip wheel PyGithub
        shell: bash

      - name: Run Checker
        run: python ./.github/workflows/pypi_notifier.py
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
