name: 'Remove Needs Label'
on:
  issues:
    types: [closed]

jobs:
  classify:
    name: 'Remove needs labels on issue closing'
    runs-on: ubuntu-latest
    steps:
      - name: 'Remove needs labels on issue close'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: stable
          path: ./actions

    #   - name: Install Actions
    #     run: npm install --prefix ./actions

      - name: Remove Any Needs Labels
        uses: ./actions/python-remove-needs-label
