name: 'Remove Needs Label'
on:
  issues:
    types: [closed]

jobs:
  classify:
    name: 'Remove needs labels on issue clos'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: stable
          path: ./actions

      - name: Install Actions
        run: npm install --production --prefix ./actions

      - name: Classify PR
        uses: ./actions/python-remove-needs-label
