name: 'Telemetry'
on:
  pull_request:
  # paths:
  #   - 'src/client/telemetry/*.ts'
  push:
    branches-ignore:
      - main
      - release*
    paths:
      - 'src/client/telemetry/*.ts'

jobs:
  check-metdata:
    name: 'Check metadata'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: npm i @vscode/telemetry-extractor

      - run: npx "@vscode/telemetry-extrator" -s src/client/telemetry
