name: Packages Update Check

on:
    schedule:
        # Run at UTC 00:00 Mon-Fri
        - cron: '0 0 * * 1-5'

jobs:
    check-PyPI:
        name: Check for package updates on PyPI and create issue
        runs-on: ubuntu-latest
        permissions:
            issues: write

